---
title: "p8105_hw2_CSL2209"
author: "Casandra Laney"
date: "2025-10-01"
output: github_document
---

```{r}
library(tidyverse)
library(readxl)
library(haven)
```


## Problem 1
clean the data in pols-month.csv

```{r}
pols_month_df = read.csv("data/pols-month.csv") |>
  janitor::clean_names() |>
  separate(mon, into = c("year", "month", "day"), sep = '-'
  ) |>
  mutate(
    month =
      case_match(
        month,
        "01" ~ "jan",
        "02" ~ "feb",
        "03" ~ "mar",
        "04" ~ "apr",
        "05" ~ "may",
        "06" ~ "jun",
        "07" ~ "jul",
        "08" ~ "aug",
        "09" ~ "sept",
        "10" ~ "oct",
        "11" ~ "nov",
        "12" ~ "dec"),
    month = as.factor(month),
    year = as.integer(year),
    day = as.integer(day),
    president = 
      case_match (
        prez_gop,
        1 ~ "gop",
        0 ~ "dem")) |>
  select(-day, -prez_dem, -prez_gop)
```

clean the data in snp.csv

```{r}
snp_df = read.csv("data/snp.csv") |>
  janitor::clean_names() |>
  separate(date, into = c("month", "day", "year"), sep = '/') |>
  mutate(
    month =
      case_match(
        month,
        "1" ~ "jan",
        "2" ~ "feb",
        "3" ~ "mar",
        "4" ~ "apr",
        "5" ~ "may",
        "6" ~ "jun",
        "7" ~ "jul",
        "8" ~ "aug",
        "9" ~ "sept",
        "10" ~ "oct",
        "11" ~ "nov",
        "12" ~ "dec"),
    month = as.factor(month),
    year = as.integer(year),
    day = as.integer(day),
    year = ifelse(year < 50, year + 2000, year + 1900)
  ) |>
  select(year, month, close, -day) 
```

tidy the unemployment data 

```{r}
unemployment_df = read.csv("data/unemployment.csv") |>
  janitor::clean_names() |>
  pivot_longer(
    jan:dec,
    names_to = "month",
    values_to = "unemployment")
```

Join the datasets

```{r}
pols_snp = left_join(pols_month_df, snp_df, by = c("year", "month"))

five_thirty_eight = left_join(pols_snp, unemployment_df, by = c("year", "month"))
```


About these datasets


## Problem 2

Read and clean the Mr. Trash, Professor, and Gwynnda sheets

```{r}
mr_trash_wheel = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Mr. Trash Wheel", skip = 1) |>
  janitor::clean_names() |>
  select(-x15, -x16) |>
  drop_na(dumpster) |>
  mutate(
    month = as.factor(month),
    year = as.integer(year),
    sports_balls = as.integer(sports_balls),
    wheel = "mr_trash") 

professor_trash_wheel = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Professor Trash Wheel", skip = 1) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    month = as.factor(month),
    year = as.integer(year),
    wheel = "professor"
  )
  
gwynnda = 
  read_excel("data/202509 Trash Wheel Collection Data.xlsx", sheet = "Gwynns Falls Trash Wheel", skip = 1) |>
  janitor::clean_names() |>
  drop_na(dumpster) |>
  mutate(
    month = as.factor(month),
    year = as.integer(year),
    wheel = "gwynnda"
  )

```

Combine the three datasets into one

```{r}
tidy_wheels = 
  bind_rows(mr_trash_wheel, professor_trash_wheel, gwynnda) |>
  janitor::clean_names()
```

## Problem 3
